#+TITLE: Vagrant / Ansible easy setup for TTM

* What is this?

This is a quick-to-setup-and-tear-down vagrant + ansible setup for the
TTM project.

* How to use it

Check out this repository, cd to the base directory of it.

** Set up the vagrant image

You'll need a properly configured debian wheezy image titled
"vagrant-debian-wheezy" with a vagrant user that has sudo permissions.

The key for this vagrant user should be at: ~/.ssh/vagrant

Making this image is the most complex part (you could use a prebuilt
image, but I don't trust them).  Once you have it, the rest is easy
peasy.

To set up the image, run:

: vagrant up && vagrant ssh -c /vagrant/ansible/scripts/setup_dev_db.sh

You're done!

You should be able to open the test site at http://127.0.0.1:8080/ in
your browser.

Your checkout of this codebase is mounted inside the vagrant VM image
and connected to apache, so you can hack away with all your local tools!

** Using

If you want to shut down the vm, try:

: vagrant halt

To bring it back up again:

: vagrant up

If you update the ansible rules, you can re-run provisioning:

: vagrant provision

Don't need this vm anymore?

: vagrant destroy

You can always go back through the setup steps again.

For more info:

: vagrant --help

